# Generated by Django 3.2.9 on 2021-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='returned',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
