# Generated by Django 3.2.9 on 2021-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_farmer_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='returned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
